### ISSUE TITLE
document.body is null in cordova!

### ISSUE THREAD

**Issue by fangjj** [aruntk/meteor-cordova-body-test#1]
http://stackoverflow.com/questions/36423430/document-body-is-null-in-cordova-in-meteor-1-3
i hit the same problem as you, can you fixed it ?

**Comment by aruntk** [comment]
check the answer in the stack post http://stackoverflow.com/a/36425409/3815092

**Comment by fangjj** [comment]
document.addEventListener("deviceready",onDeviceReady,false);
function onDeviceReady(){
    ReactDOM.render(routes, document.getElementById('sk-root'));
}
if i do that ,it's not working fine in web browsers.

**Comment by aruntk** [comment]
Put that inside if(Meteor.isCordova){
}

**Comment by fangjj** [comment]
thank you! you're so nice!

**Comment by aruntk** [comment]
@fangjj :)
